NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.infrastructure.reliance-network.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.infrastructure.reliance-network.com-cert.pem
    OrganizationalUnitIdentifier: peer
